version: '3.8'

services:
  sergioykathe: &sergioykathe
    build:
      context: .
      dockerfile: ./sergioykathe/Dockerfile
    working_dir: /app
    volumes:
      - ../..:/app
    ports:
      - '4444:4321'
      - '9000:8969'
    env_file:
      - sergioykathe/.env
    command:
      - /bin/sh
      - -c
      - |
        sleep infinity
